improvement/display info about created keyword from contextMenu
PatrykKuniczak/YT_Notifier pull request #179
Opened 2023-11-29 12:23 UTC by TheMadNerd

#175

2023-11-29 21:05 UTC, PatrykKuniczak requested changes
Don't work to me, i have that errors on the console:

![image](https://github.com/PatrykKuniczak/YT_Search_Plugin/assets/64608510/97627ee0-9546-4f6d-bed3-0481222641e6)

2023-12-02 15:02 UTC, PatrykKuniczak commented
I have it also on my branch, that's merged into dev before, but overall check that error

2023-12-10 12:58 UTC, PatrykKuniczak approved these changes
LGTM

2023-12-10 15:11 UTC, masterHAWK99 approved these changes

2023-12-10 15:30 UTC, merged